version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      ignore_warnings: true
      file_extensions: "php"
      standard: "WordPress-Core"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
